### ISSUE TITLE
编译脚本中edk2的路径问题

### ISSUE THREAD

**Issue by a1ive** [ventoy/vdiskchain#3]
https://github.com/ventoy/vdiskchain/blob/5228721df26c9fe9d0ea00721da1d97c0912e119/build_image.sh#L95-L104
edk2 所在的文件夹名称应为 EDK2，而不是 EDKII，应该和 Ventoy 项目中的路径保持一致：
https://github.com/ventoy/Ventoy/tree/master/EDK2

**Comment by ventoy** [comment]
已经修改
